package it.polimi.ingsw.network.enumeration;

public enum ActionType {
    DISCARDLEADER,PLAYLEADER,MARKETACTION,MOVEFROMDEPOSITTOLEADER,MOVEFROMLEADERTODEPOSIT,ORGANIZESTORAGE,
    BASICPRODUCTION,DEVCARDPRODUCTION,LEADERPRODUCTION,CARDSHOP,END;
}
