package it.polimi.ingsw.network.enumeration;

public enum PlayerUpdateType {
    CHEST,BUFFERPRODUCTION,INITARRAYDEPOSIT,ARRAYDEPOSIT,DEVCARDS,DISCARDLEADER,
    PATHPOSITION,INGAMELEADER,FIRSTROW,SECONDROW,THIRDROW;
}
