package it.polimi.ingsw.network.enumeration;

public enum ServerMessageType {
    PRINTMESSAGE, LOBBIES, JOINEDLOBBY, YOURTURN, PREGAME, SHOPUPDATE, PLAYERUPDATE, MARKETUPDATE,
    INITGAMESTATUS,WAITYOURTURN,ENDSINGLEPLAYERGAME,ENDMULTIPLAYERGAME;
}
