package it.polimi.ingsw.network.enumeration;

public enum ServerMessageType {
    PRINTMESSAGE, LOBBIES, JOINEDLOBBY, YOURTURN, PREGAME, SHOPUPDATE, PLAYERUPDATE, MARKETUPDATE,VATICANREPORT,
    INITGAMESTATUS,WAITYOURTURN,ENDSINGLEPLAYERGAME,ENDMULTIPLAYERGAME,STARTGAME;
}
