package it.polimi.ingsw.network.enumeration;

public enum ServerMessageType {
    PRINTMESSAGE, LOBBIES, JOINEDLOBBY, YOURTURN, PING, PREGAME, SHOPUPDATE, PLAYERUPDATE, MARKETUPDATE,
    INITGAMESTATUS,WAITYOURTURN,ENDSINGLEPLAYERGAME,ENDMULTIPLAYERGAME,INITKNOWNPLAYER;
}
